name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
    
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run Unit Tests & Generate Coverage Report
        run: |
          go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=yishu1606
            -Dsonar.projectKey=yishvendrabaghel_DevOps-CI-CD
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out

  build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build
        run: go build -o project-2

      - name: Test
        run: go test ./...

  push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push actions
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/project-2:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" helm/project-2-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "ykbskb@gmail.com"
          git config --global user.name "Yishvendra"
          git add helm/project-2-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git pull --rebase origin main # Pull latest changes before pushing
          git push


#hello
